### ISSUE TITLE
Isn't text node supported?

### ISSUE THREAD

**Issue by panlina** [1904labs/dom-to-image-more#62]
### Use case

[jsfiddle](https://jsfiddle.net/2c4sy83u/2/)

Render a text node.

I know wrapping it with a span can make it render, but what I'm working on is a developer tool, so I want to be able to take screenshot of any DOM node including text node.

### Expected behavior

Render correctly.

### Actual behavior

Fail to render.

On chrome it gives:

> Failed to execute 'appendChild' on 'Node': This node type does not support this method.

The source location is:

https://github.com/1904labs/dom-to-image-more/blob/47deed22b9ad731f08beed25a2b1a141e653a9f4/src/dom-to-image-more.js#L409

Seems it does not take into account the case of text node and tries to add a style element into it.

Is it difficult to make it support text node?

### Library version

2.9.5

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+

**Comment by Clive-Ward-Cron** [comment]
@panlina for my use case wrapping it in a span is working, but I'd like to know if you found an alternative approach of your own.

The way I'm doing it is when I get to a text node that I want to use domtoimage on, I'm creating a span with JS and appending the text node to it. Then I'm appending that span to the text node's original parent. After that I'm passing the span with the text node to domtoimage. I suppose I could undo those DOM changes, but I don't think that its necessary for my use case.

Either way it feels like a lot of extra work to be performed for something that seems like it should work out of the box.

I think the problem might be that the function needs to add the style element to it to preserve any styles applied to the passed node so that the image output actually matches the element on the page.

**Comment by IDisposable** [comment]
Working on a fix for this now.

**Comment by IDisposable** [comment]
PR #117 will fix this... but really curious about the use case for this (why would you want an image of some bare text)?
